# Generated by Django 4.1.7 on 2023-03-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(default='xyz@abc.com', max_length=254)),
                ('spam', models.BooleanField(default=False)),
            ],
        ),
    ]
