# Generated by Django 4.1.7 on 2023-03-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerusermodel',
            old_name='user_name',
            new_name='username',
        ),
    ]
